version: '3.7'

services:

  php-fpm:
    container_name: php-symfony
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src/symfony:/var/www/html/symfony
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - docker-cms-symfony

  nginx:
    container_name: nginx-symfony
    image: nginx:stable
    ports:
      - '81:81'
    volumes:
      - ./src/symfony:/var/www/html/symfony
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - docker-cms-symfony

  db:
    container_name: mysql-symfony
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - docker-cms-symfony


  adminer:
    container_name: adminer-symfony
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: database
      ADMINER_DESIGN: haeckel
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - 33061:8080
    networks:
      - docker-cms-symfony

  mailpit:
    container_name: mailpit-symfony
    image: 'axllent/mailpit:latest'
    restart: unless-stopped
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - docker-cms-symfony

  redis:
    container_name: redis-symfony
    image: 'redis:7-alpine'
    restart: unless-stopped
    command:
      [
        "redis-server",
        "--bind",
        "0.0.0.0",
        "--appendonly",
        "yes"
      ]
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
    volumes:
      - ./docker/redis:/data
    networks:
      - docker-cms-symfony

networks:
  docker-cms-symfony:
    driver: bridge
